# Generated by Django 5.1.5 on 2026-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deletedbooking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deletedbooking',
            name='start_date',
            field=models.DateField(),
        ),
    ]
