# Generated by Django 5.1.5 on 2026-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('car_owner', 'Car Owner'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
