# Generated by Django 5.1.5 on 2026-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('car_owner', 'Car Owner'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='customer', max_length=20),
        ),
    ]
