# Generated by Django 5.1.5 on 2026-03-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carBrand', models.CharField(max_length=100)),
                ('carModel', models.CharField(max_length=100)),
                ('carCategory', models.CharField(max_length=100)),
                ('carYear', models.IntegerField()),
                ('carKM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carFuelType', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='profiles.profile')),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-carYear'],
            },
        ),
    ]
