# Generated by Django 5.1.5 on 2026-03-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carBrand', models.CharField(choices=[('mercedes', 'Mercedes-Benz'), ('bmw', 'BMW'), ('audi', 'Audi'), ('toyota', 'Toyota'), ('honda', 'Honda'), ('volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('lexus', 'Lexus'), ('porsche', 'Porsche'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('maserati', 'Maserati'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('volvo', 'Volvo'), ('subaru', 'Subaru'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('fiat', 'Fiat'), ('alfa_romeo', 'Alfa Romeo'), ('seat', 'SEAT'), ('skoda', 'Skoda'), ('tesla', 'Tesla'), ('jeep', 'Jeep'), ('dodge', 'Dodge'), ('chrysler', 'Chrysler'), ('cadillac', 'Cadillac'), ('buick', 'Buick'), ('infiniti', 'Infiniti'), ('acura', 'Acura'), ('genesis', 'Genesis'), ('bentley', 'Bentley'), ('rolls_royce', 'Rolls-Royce'), ('aston_martin', 'Aston Martin'), ('mclaren', 'McLaren'), ('bugatti', 'Bugatti'), ('lada', 'Lada'), ('opel', 'Opel')], max_length=100)),
                ('carModel', models.CharField(choices=[('c180', 'C180'), ('c200', 'C200'), ('c250', 'C250'), ('c300', 'C300'), ('e200', 'E200'), ('e250', 'E250'), ('e300', 'E300'), ('e350', 'E350'), ('s350', 'S350'), ('s450', 'S450'), ('s500', 'S500'), ('s600', 'S600'), ('gle300', 'GLE 300'), ('gle350', 'GLE 350'), ('gle450', 'GLE 450'), ('glc200', 'GLC 200'), ('glc300', 'GLC 300'), ('cla180', 'CLA 180'), ('cla200', 'CLA 200'), ('cla250', 'CLA 250'), ('a180', 'A180'), ('a200', 'A200'), ('a250', 'A250'), ('bmw_118i', '118i'), ('bmw_120i', '120i'), ('bmw_320i', '320i'), ('bmw_330i', '330i'), ('bmw_340i', '340i'), ('bmw_520i', '520i'), ('bmw_530i', '530i'), ('bmw_540i', '540i'), ('bmw_550i', '550i'), ('bmw_730i', '730i'), ('bmw_740i', '740i'), ('bmw_750i', '750i'), ('bmw_x3', 'X3'), ('bmw_x5', 'X5'), ('bmw_x6', 'X6'), ('bmw_x7', 'X7'), ('bmw_m3', 'M3'), ('bmw_m5', 'M5'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('a6', 'A6'), ('a7', 'A7'), ('a8', 'A8'), ('q3', 'Q3'), ('q5', 'Q5'), ('q7', 'Q7'), ('q8', 'Q8'), ('rs3', 'RS3'), ('rs6', 'RS6'), ('tt', 'TT'), ('r8', 'R8'), ('camry', 'Camry'), ('corolla', 'Corolla'), ('yaris', 'Yaris'), ('rav4', 'RAV4'), ('land_cruiser', 'Land Cruiser'), ('prado', 'Land Cruiser Prado'), ('highlander', 'Highlander'), ('fortuner', 'Fortuner'), ('prius', 'Prius'), ('avalon', 'Avalon'), ('civic', 'Civic'), ('accord', 'Accord'), ('hrv', 'HR-V'), ('crv', 'CR-V'), ('pilot', 'Pilot'), ('jazz', 'Jazz'), ('golf', 'Golf'), ('passat', 'Passat'), ('jetta', 'Jetta'), ('tiguan', 'Tiguan'), ('touareg', 'Touareg'), ('polo', 'Polo'), ('focus', 'Focus'), ('fusion', 'Fusion'), ('mustang', 'Mustang'), ('explorer', 'Explorer'), ('escape', 'Escape'), ('f150', 'F-150'), ('elantra', 'Elantra'), ('sonata', 'Sonata'), ('tucson', 'Tucson'), ('santafe', 'Santa Fe'), ('i30', 'i30'), ('i10', 'i10'), ('sportage', 'Sportage'), ('sorento', 'Sorento'), ('cerato', 'Cerato'), ('optima', 'Optima'), ('stinger', 'Stinger'), ('telluride', 'Telluride'), ('lexus_es300', 'ES300'), ('lexus_es350', 'ES350'), ('lexus_rx300', 'RX300'), ('lexus_rx350', 'RX350'), ('lexus_rx450', 'RX450h'), ('lexus_ls460', 'LS460'), ('lexus_lx570', 'LX570'), ('cayenne', 'Cayenne'), ('macan', 'Macan'), ('panamera', 'Panamera'), ('911', '911'), ('taycan', 'Taycan'), ('model_s', 'Model S'), ('model_3', 'Model 3'), ('model_x', 'Model X'), ('model_y', 'Model Y'), ('qashqai', 'Qashqai'), ('xtrail', 'X-Trail'), ('altima', 'Altima'), ('maxima', 'Maxima'), ('pathfinder', 'Pathfinder'), ('patrol', 'Patrol'), ('lada_vesta', 'Vesta'), ('lada_granta', 'Granta'), ('lada_niva', 'Niva'), ('astra', 'Astra'), ('insignia', 'Insignia'), ('mokka', 'Mokka')], max_length=100)),
                ('carCategory', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('offroad', 'Off-Road'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Station Wagon'), ('minivan', 'Minivan'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('sports', 'Sports Car'), ('luxury', 'Luxury'), ('electric', 'Electric')], max_length=100)),
                ('carYear', models.IntegerField(choices=[(1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)])),
                ('carKM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carFuelType', models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('diesel', 'Diesel'), ('gas', 'Gas')], max_length=50, null=True)),
                ('bensinType', models.CharField(blank=True, choices=[('92', 'Benzin 92'), ('95', 'Benzin 95'), ('98', 'Benzin 98')], max_length=50, null=True)),
                ('carType', models.CharField(choices=[('none', 'None'), ('hibrid', 'Hibrid'), ('plugin_hibrid', 'Plugin Hibrid'), ('elektrik', 'Elektrik')], default='none', max_length=50)),
                ('karopkaType', models.CharField(choices=[('avtomat', 'Avtomat'), ('mexaniki', 'Mexaniki')], max_length=50)),
                ('dailyRentPrice', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('carLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('carIdNumber', models.CharField(default=None, max_length=100)),
                ('carRegistrationNumber', models.CharField(default=None, max_length=100)),
                ('carColor', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('beige', 'Beige'), ('gold', 'Gold'), ('purple', 'Purple'), ('pink', 'Pink'), ('other', 'Other')], default=None, max_length=100)),
                ('carMotor', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carSits', models.IntegerField(default=5)),
                ('isPersonal', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='profiles.profile')),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-carYear'],
            },
        ),
        migrations.CreateModel(
            name='DeletedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_car_id', models.IntegerField()),
                ('carBrand', models.CharField(max_length=100)),
                ('carModel', models.CharField(max_length=100)),
                ('carCategory', models.CharField(max_length=100)),
                ('carYear', models.IntegerField()),
                ('carKM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carFuelType', models.CharField(blank=True, max_length=50, null=True)),
                ('bensinType', models.CharField(blank=True, max_length=50, null=True)),
                ('carType', models.CharField(max_length=50)),
                ('karopkaType', models.CharField(max_length=50)),
                ('dailyRentPrice', models.DecimalField(decimal_places=0, max_digits=10)),
                ('carLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('carIdNumber', models.CharField(max_length=100)),
                ('carRegistrationNumber', models.CharField(max_length=100)),
                ('carColor', models.CharField(max_length=100)),
                ('carMotor', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carSits', models.IntegerField()),
                ('isPersonal', models.CharField(max_length=10)),
                ('owner_username', models.CharField(max_length=150)),
                ('owner_full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Car',
                'verbose_name_plural': 'Deleted Cars',
                'db_table': 'deleted_cars',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
