# Generated by Django 5.1.5 on 2026-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bensinType',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='karopkaType',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
