# Generated by Django 5.1.5 on 2026-03-11 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_carcolor_car_caridnumber_car_carmotor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_car_id', models.IntegerField()),
                ('carBrand', models.CharField(max_length=100)),
                ('carModel', models.CharField(max_length=100)),
                ('carCategory', models.CharField(max_length=100)),
                ('carYear', models.IntegerField()),
                ('carKM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carFuelType', models.CharField(blank=True, max_length=50, null=True)),
                ('bensinType', models.CharField(blank=True, max_length=50, null=True)),
                ('carType', models.CharField(max_length=50)),
                ('karopkaType', models.CharField(max_length=50)),
                ('dailyRentPrice', models.DecimalField(decimal_places=0, max_digits=10)),
                ('carIdNumber', models.CharField(max_length=100)),
                ('carRegistrationNumber', models.CharField(max_length=100)),
                ('carColor', models.CharField(max_length=100)),
                ('carMotor', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carSits', models.IntegerField()),
                ('isPersonal', models.CharField(max_length=10)),
                ('owner_username', models.CharField(max_length=150)),
                ('owner_full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Car',
                'verbose_name_plural': 'Deleted Cars',
                'db_table': 'deleted_cars',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
